# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e286b0fdde8725b454622bae191ed9077a2927c7ae536d9259b8d69bf08c5fd50ac4d6e6a4d011a89f501eae7cbd9f80224383b1a2da4b4ff6e3d5d06c63651

test:
  secret_key_base: 86ea14190bf5212af5c666bd6b4b428ef453223613c26bc6b6454f7752e99321dacfbc8cb8b90c7725a612eb1c5d4cf413dff3cd87f2698e41f064e71cd67109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
